language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
yarn: true
before_script: yarn build && yarn build-storybook
script:
  - GIT_HASH=$(git rev-parse --short HEAD)
  - echo ${GIT_HASH} > build/version
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then BUILD_URL=$(npx now --name app.mybit.io build -t $NOW_PROD_TOKEN); fi
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then STORYBOOK_URL=$(npx now --name storybook.mybit.io build -t $NOW_PROD_TOKEN); fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${BUILD_URL} app-staging.mybit.io -t $NOW_PROD_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${STORYBOOK_URL} storybook-staging.mybit.io -t $NOW_PROD_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${BUILD_URL} app.mybit.io -t $NOW_PROD_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${STORYBOOK_URL} storybook.mybit.io -t $NOW_PROD_TOKEN; fi
